{{- if not .Values.database.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "umami.database.secretName" . }}
data:
  {{ include "umami.database.databaseUrlKey" . }}: {{ include "umami.database.url" . | b64enc }}
{{- end }}
